### ISSUE TITLE
Implement JSDocs

### ISSUE THREAD

**Issue by RamonGebben** [Rabrennie/anything.js#222]
It would save a lot of time on documenting when you force to include JSdoc comments.
We do need to implement that and generate it onto the website.

**Comment by Rabrennie** [comment]
Yeah I agree. I don't know what we'll do for all the functions that are already there though.

**Comment by gytdau** [comment]
I'm not sure about having _forced_ documentation. I feel like it would take out the fun of it for many of the joke functions, which anything.js has a lot of.

I would prefer  _optional_ documentation - some functions are more 'serious' and in that case documentation would be suitable.

**Comment by dstrekelj** [comment]
You can always put off merging pull requests that lack proper commenting until the contributor adds them. Especially if the contribution is large and / or complex.

A good first step would be adding a rule about commenting code to the contributing guidelines.

**Comment by gytdau** [comment]
My opinion is simple: we shouldn't reject code without documentation. Having a rule that forces documentation would, in my opinion, violate the spirit of anything.js.

**Comment by Rabrennie** [comment]
I think for the time being I will add the ability to auto generate docs from available jsdocs but not force it on users.

**Comment by developer787** [comment]
anything should be as organic as possible. It will "slowly" grow and evolve into and organized API.

**Comment by vccortez** [comment]
I think it would be cool to enable auto generated JSDocs.

That way, the developers themselves could implement the doc of their functions **if** they want it.

**Comment by RamonGebben** [comment]
Pull request ready #240

**Comment by Rabrennie** [comment]
done
