### ISSUE TITLE
Auto update gh-pages

### ISSUE THREAD

**Issue by vccortez** [Rabrennie/anything.js#264]
Since the [anythingjs.io](http://anythingjs.io) website is based on the files inside the `gh-pages` branch, we need a way to update the `dist` folder of that branch after we build a new `anything.min.js` file.

Any thoughts or ideas?

**Comment by Rabrennie** [comment]
This will be done soon maybe later today.

**Comment by vccortez** [comment]
Cool, if you need any help I will be available tonight.

**Comment by Rabrennie** [comment]
Alright. I'll talk to you on irc if you're on later

**Comment by developer787** [comment]
I would like to help on irc now

**Comment by arkon** [comment]
This is probably useful: https://www.npmjs.com/package/gulp-gh-pages

**Comment by vccortez** [comment]
That looks like a good solution.

**Comment by vccortez** [comment]
Hey @Rabrennie, what is the `[...] master > /dev/null 2>&1` part in line 13 of **deploy.sh** doing exactly?

Edit: Whoops, that close issue button is not very well placed.

**Comment by vccortez** [comment]
If anyone could take a look at the changes in #344 and test it, that would be great.

I actually am not able to test that in this very moment.

**Comment by arkon** [comment]
@vekat The `[...] master > /dev/null 2>&1` just makes it so the stdout/stderr disappears into the nether.

**Comment by vccortez** [comment]
thanks mate.

**Comment by vccortez** [comment]
so it is a regular push command.

**Comment by TheBITLINK** [comment]
Since we now use rawgit, this is no longer necessary.
