### ISSUE TITLE
Build process. None of these so called memes pls

### ISSUE THREAD

**Issue by Rabrennie** [Rabrennie/anything.js#27]
Each function is it's own file and automatically gets added to the lib on build.

**Comment by Rabrennie** [comment]
This will(should) cut down on the number of merge conflicts

**Comment by gytdau** [comment]
This is a good idea.

**Comment by Rabrennie** [comment]
D U N

**Comment by gytdau** [comment]
YES. FINALLY. WE DID IT GUYS. THANK YOU. 

I would like to thank my mother for all the spaghetti she made me.

**Comment by thehowl** [comment]
Hello? Spaghetti? Who said spaghetti? I'm up for some.

**Comment by gytdau** [comment]
[S](https://www.youtube.com/watch?v=SW-BU6keEUw)p[a](http://memesvault.com/wp-content/uploads/Frog-Meme-Spaghetti-29.jpg)g[h](http://imgur.com/gallery/Yq9u0Hq)etti.

**Comment by gytdau** [comment]
:musical_note: :musical_note: 
You better lose yourself with your mom's spaghetti.
It's ready.
You better never let it go!  

You only get one spaghetti.
Do not miss your chance to blow;
'coz spaghetti comes once in a lifetime, yo!
:musical_note: :musical_note:

**Comment by thehowl** [comment]
[BARNEY IS A DINOSAUR FROM OUR IMMAGINATION](https://www.youtube.com/watch?v=lr-l7ycJTaw)
