### ISSUE TITLE
Create 404 page

### ISSUE THREAD

**Issue by ghost** [Rabrennie/anything.js#292]

**Comment by vccortez** [comment]
I had a 404 page example somewhere, but my file was not found.

**Comment by ghost** [comment]
I personally think that the 404 page should demonstrate some of the amazing features. preferably anything.imDrunk()

**Comment by ndaigneault** [comment]
I personally think that the 404 page should demonstrate some of the amazing features. preferably anything.imDrunk()

**Comment by ghost** [comment]
i accidentally closed this issue, i can't github this morning :(

**Comment by vccortez** [comment]
lol @ndaigneault :laughing:

**Comment by gytdau** [comment]
I've reopened it for you.

**Comment by gytdau** [comment]
It's been 13 days - I'm closing this issue because I assume nobody really cares enough anymore.

**Comment by Rabrennie** [comment]
@gytdau stop closing issues that aren't fixed

**Comment by TheBITLINK** [comment]
it ugly

**Comment by Rabrennie** [comment]
pls m8

**Comment by TheBITLINK** [comment]
#162

**Comment by SCKelemen** [comment]
This was fixed by: #404 
We can close this issue.
