### ISSUE TITLE
johnCena is broken

### ISSUE THREAD

**Issue by Rabrennie** [Rabrennie/anything.js#397]
no images showing, lots of errors in console

https://github.com/Rabrennie/anything.js/blob/master/src/johnCena.js

**Comment by TheBITLINK** [comment]
No, nevermind

**Comment by vccortez** [comment]
Tried with #398.

**Comment by TheBITLINK** [comment]
same thing

**Comment by vccortez** [comment]
Did it work? Update the gh-pages.

**Comment by TheBITLINK** [comment]
I did a commit yesterday that makes the playground always use the latest build on the master branch.

**Comment by TheBITLINK** [comment]
I think this is where the real error is

``` javascript
var imgs = Array.prototype.slice.call(s.get("div")).concat(Array.prototype.slice.call(s.get("body")));
```

What is the `s` variable supposed to represent?

**Comment by vccortez** [comment]
It is either caching the old version or not working then, as I look into the minified file (prettyfied) and the `var i` isn't there.

**Comment by TheBITLINK** [comment]
It _is_ caching the old version

**Comment by vccortez** [comment]
Then we need to update it @TheBITLINK ! So we can test the commit.

`s` is effectively the object `{ get: function(selector) { return document.querySelectorAll.call(document, selector); } };`, it seems.

Edit: missed a return.

**Comment by Rabrennie** [comment]
it's fixed
