### ISSUE TITLE
Not Found

### ISSUE THREAD

**Issue by gytdau** [Rabrennie/anything.js#404]
The document you are trying to reach has been moved or no longer exists.

**Comment by Rabrennie** [comment]
Heh

**Comment by ghost** [comment]
Oh dear.. Sorry we couldn't find that page.

**Comment by TheBITLINK** [comment]
I had an idea!

Why not make 404s on anythingjs.io redirect to this issue?

**Comment by ghost** [comment]
Great idea! make a PR then!

**Comment by Rabrennie** [comment]
done #406

**Comment by gytdau** [comment]
guys pull request 400 is coming soon, someone here better make it good

**Comment by TheBITLINK** [comment]
![screenshot from 2016-10-07 18-24-27](https://cloud.githubusercontent.com/assets/3434300/19207045/52a9c4e6-8cbb-11e6-9699-816fa8698bd9.png)

**_[HYPED]**_

**Comment by SCKelemen** [comment]
Well, the shenanigans were quality, while they lasted.
