### ISSUE TITLE
Website can’t be reached

### ISSUE THREAD

**Issue by CVarisco** [Rabrennie/anything.js#448]
Hi guys 🙂 

The http://anythingjs.io/ can't be reached.
<img width="1041" alt="screen shot 2017-07-14 at 12 15 21" src="https://user-images.githubusercontent.com/7335613/28208510-4bdacf70-688e-11e7-98a1-594ba1a4b630.png">

**Comment by gytdau** [comment]
Tsk tsk @Rabrennie, cough up those domain fees.

**Comment by Rabrennie** [comment]
Domains are expensive :(

**Comment by gytdau** [comment]
Such is the cost of greatness.

**Comment by CVarisco** [comment]
If you use the github page ?
it's free and good enough 🌮 

What do you think ?

**Comment by Rabrennie** [comment]
url will now be http://rabrennie.com/anything.js

**Comment by SCKelemen** [comment]
I can donate money for the domain...

**Comment by Rabrennie** [comment]
I'm in the process of moving all my stuff to AWS. I'll get this put over soon™

**Comment by Rabrennie** [comment]
New issue #459
