### ISSUE TITLE
Website broke again

### ISSUE THREAD

**Issue by TheBITLINK** [Rabrennie/anything.js#459]
![image](https://user-images.githubusercontent.com/3434300/32255700-96331e4a-be80-11e7-8dcb-d5553e5eeab4.png)
fix ur shite

**Comment by SCKelemen** [comment]
Why was this assigned to me?

**Comment by Rabrennie** [comment]
I'm in the process of moving all my stuff to AWS. I'll get this put over soon™

**Comment by TheBITLINK** [comment]
day 5, still not done

**Comment by SCKelemen** [comment]
Now it's day 11.

**Comment by Rabrennie** [comment]
No internet till Wednesday boys

**Comment by TheBITLINK** [comment]
![image](https://user-images.githubusercontent.com/3434300/33141340-3da36ba8-cf89-11e7-8611-9cbb72ef25f9.png)

**Comment by gytdau** [comment]
He never specified which Wednesday. False alarm.

**Comment by TheBITLINK** [comment]
Alright, since this is never going to get done™, i just made a mirror

https://Δ.thebit.link/

**Comment by Rabrennie** [comment]
@TheBITLINK ty

**Comment by Rabrennie** [comment]
Fixed it.... 

after a year.


http://rabrennie.com/anything.js.
